---oracle index
SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'MEMBERS';

SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'MEMBERS';
    
SELECT * FROM members
WHERE last_name = 'Harse';    

SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());

DROP INDEX members_last_name_i;    

CREATE INDEX members_name_i
ON members(last_name,first_name);

SELECT * 
FROM members
WHERE last_name LIKE 'A%' 
    AND first_name LIKE 'M%';
    
EXPLAIN PLAN FOR
SELECT * 
FROM members
WHERE last_name LIKE 'A%' 
    AND first_name LIKE 'M%';
    
    
SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY()); 
    
--unique index
CREATE UNIQUE INDEX members_email_i
ON members(email);

INSERT INTO members(first_name, last_name, gender, dob, email)
VALUES('Pegpa','Elce','F',DATE '1990-01-02','pelce0@trellian.com');

CREATE TABLE unq_idx_demo(
    a INT,
    b INT
);   

CREATE UNIQUE INDEX unq_idx_demo_ab_i
ON unq_idx_demo(a,b);

INSERT INTO unq_idx_demo(a,b)
VALUES(1,1);
INSERT INTO unq_idx_demo(a,b)
VALUES(1,2);
--already exist so gives error
INSERT INTO unq_idx_demo(a,b)
VALUES(1,1);

CREATE TABLE t1 (
    pk1 INT PRIMARY KEY,
    c1 INT
);

SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'T1';
    
CREATE TABLE t2 (
    pk2 INT PRIMARY KEY 
        USING INDEX (
            CREATE INDEX t1_pk1_i ON t2 (pk2)
    ),
    c2 INT
);   
SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'T2';
    
--function based index

CREATE INDEX members_last_name_i 
ON members(last_name);
SELECT * FROM members
WHERE last_name = 'Sans';
SELECT * FROM members
WHERE UPPER(last_name) = 'SANS';
EXPLAIN PLAN FOR
SELECT * FROM members
WHERE UPPER(last_name) = 'SANS';


SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
--Oracle function-based index example
CREATE INDEX members_last_name_fi
ON members(UPPER(last_name));

EXPLAIN PLAN FOR
SELECT * FROM members
WHERE UPPER(last_name) = 'SANS';

SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
-- Oracle bitmap index
SELECT 
    *
FROM
    members
WHERE
    first_name = 'Harse';
    
CREATE BITMAP INDEX members_first_name_i
ON members(first_name);    

EXPLAIN PLAN FOR 
SELECT 
    *
FROM
    members
WHERE
    first_name = 'Harse';

    
SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
 CREATE TABLE bitmap_index_demo(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    active NUMBER NOT NULL,
    PRIMARY KEY(id)
);   

CREATE BITMAP INDEX bitmap_index_demo_active_i
ON bitmap_index_demo(active);

INSERT INTO bitmap_index_demo(active) 
VALUES(1);

INSERT INTO bitmap_index_demo(active) 
VALUES(0);

--fetch
SELECT
	ename,
	sal
FROM
	emp
INNER JOIN deptno
		USING(empno)
ORDER BY
	sal DESC ;
--LIMIT 2000;